version: "3.7"

services:

  github-actions-runner:
    container_name: github-actions-runner-1
    build: 
      context: .
      args:
        - RUNNER_VERSION=2.304.0
        - TZ=Europe/London
        - DOCKER_COMPOSE_VERSION=2.2.3
        - DOCKER_SWITCH_VERSION=1.0.4
    environment:
      - RUNNER_URL=https://github.com/user/repo
      - RUNNER_TOKEN=%TOKEN%
      - RUNNER_NAME=runner-name-1
      - RUNNER_LABELS=dev,stage,etc
    restart: unless-stopped
    privileged: true
